### ISSUE TITLE
Adapter crashes when trying to save any configuration

### ISSUE THREAD

**Issue by femto11** [Apollon77/ioBroker.smartvisu#13]
When I try to save any config via the web interface, i get the following logs in iobroker (first 3 columns omitted):

> - instance system.adapter.smartvisu.0 terminated with code 0 (OK)
> - Caught by controller[0]: at Pipe.onread (net.js:601:20)
> - Caught by controller[0]: at Socket.Readable.push (_stream_readable.js:208:10)
> - Caught by controller[0]: at readableAddChunk (_stream_readable.js:246:13)
> - Caught by controller[0]: at addChunk (_stream_readable.js:263:12)
> - Caught by controller[0]: at Socket.emit (events.js:211:7)
> - Caught by controller[0]: at emitOne (events.js:116:13)
> - Caught by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.smartvisu/node_modules/sphp/sphp.js:557:13)
> - Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.smartvisu/node_modules/sphp/sphp.js:75:22
> - Caught by controller[0]: at ServerResponse.setHeader (_http_outgoing.js:498:3)
> - Caught by controller[0]: at validateHeader (_http_outgoing.js:487:11)
> - Caught by controller[0]: TypeError: Header name must be a valid HTTP Token ["It is called by adding '.nip.io' to the hostname, which actually is an IP number (see http"]

**Comment by Apollon77** [comment]
What config you changed where? In Smartvisu? Can you see anything that could be connected to this ".nip.io"?

**Comment by femto11** [comment]
on this page index.php?page=config 

no matter what i try to change I always end up with the same errors in the log of iobroker after I clicked on 'save settings'.

**Comment by femto11** [comment]
Sorry, but could you explain in more detail what you mean with  "Can you see anything that could be connected to this ".nip.io""?
